# -*- coding: utf-8 -*-
{
    "name": "BA Cash Control",
    "version": "13.0.0.2",
    "author": "Ing. Gabriela Rivero",
    "license": "LGPL-3",
    "category": "stock",
    "summary": """Cash Control""",
    "depends": [
        "sale_multi_store",
        "credit_card_instalment_sale",
        "l10n_ar",
        "account_payment_group",
        "account_multi_store",
    ],
    "data": [
        #'security/ir.model.access.csv',
        #'security/security.xml',
        "wizards/cash_control_transfer_wizard.xml",
        "wizards/pos_box.xml",
        "views/cash_control_config_view.xml",
        "views/cash_control_session_view.xml",
        "views/account_payment_view.xml",
        "views/cash_control_transfer_cash_view.xml",
        "views/account_journal_view.xml",
        "views/account_bnk_stmt_cashbox.xml",
        "views/sale_order.xml",
        "report/cash_control_report.xml",
        "report/report_saledetails.xml",
        "report/report_cashbox_template.xml",
        "report/report_cash_control_detail_template.xml",
        "wizards/cash_control_details.xml",
        "wizards/add_credit_note.xml",
        "views/menuitems.xml",
    ],
    "qweb": [],
    "installable": True,
}
